name: CI/ CD

on:
  push:
    branches:
      - main
    paths:
      - 'dags/**'
      - 'terraform/**'

jobs:
  lint-pyspark:
    name: Lint PySpark
    runs-on: ubuntu-latest
    if: contains(github.event.push.paths, 'dags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python linters
        run: |
          pip install flake8 isort

      - name: Run flake8
        run: flake8 dags/

      - name: Run isort
        run: isort --check-only dags/

  terraform-lint:
    name: Lint Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --version

      - name: Run TFLint
        working-directory: terraform
        run: tflint 

  sync-dags:
    name: Sync DAGs to S3
    runs-on: ubuntu-latest
    needs: [lint-pyspark, terraform-lint]
    env:
      BUCKET_NAME: big-data-bck
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1  

      - name: Sync DAGs to S3
        run: aws s3 sync dags/ s3://$BUCKET_NAME/dags/
